working_directory: &working_directory
  ~/project

defaults: &defaults
  docker:
    - image: circleci/python:3.7.0-stretch-node
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  deps-{{ '{{' }} checksum "requirements.txt" {{ '}}' }}-{{ '{{' }} checksum "requirements-dev.txt" {{ '}}' }}

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: *repo_cache_key
      - run:
          name: prepare environment
          command: make venv
      - save_cache:
          paths:
            - ./venv
          key: *repo_cache_key
      - persist_to_workspace:
          root: *working_directory
          paths: venv/*

  format:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: check formatter
          command: make lint-format

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: run linters
          command: make lint

  docs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: run doc tests
          command: make docs

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: run unit tests
          command: |
            make test
      - store_test_results:
          path: test-results
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - add_ssh_keys:
          fingerprints:
            - "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
      - run:
          name: Configure git
          command: |
            git config --global user.email "circleci@circleci.com"
            git config --global user.name "CircleCI"
      - run:
          name: Build the documentation
          command: make docs
      - run:
          name: Publish the docs
          command: make publish

workflows:
  version: 2
  gates:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - format:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - prepare
      - publish:
          requires:
            - docs
            - lint
          filters:
            branches:
              only: master
            tags:
              only: /\d\.\d\.\d/
